/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmNicknameRouteImport } from './routes/dm.$nickname'
import { Route as ChatRoomIdRouteImport } from './routes/chat.$roomId'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmNicknameRoute = DmNicknameRouteImport.update({
  id: '/dm/$nickname',
  path: '/dm/$nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomIdRoute = ChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/roulette': typeof RouletteRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/dm/$nickname': typeof DmNicknameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/roulette': typeof RouletteRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/dm/$nickname': typeof DmNicknameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/roulette': typeof RouletteRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/dm/$nickname': typeof DmNicknameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/people'
    | '/roulette'
    | '/settings'
    | '/voice'
    | '/chat/$roomId'
    | '/dm/$nickname'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/people'
    | '/roulette'
    | '/settings'
    | '/voice'
    | '/chat/$roomId'
    | '/dm/$nickname'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/people'
    | '/roulette'
    | '/settings'
    | '/voice'
    | '/chat/$roomId'
    | '/dm/$nickname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  PeopleRoute: typeof PeopleRoute
  RouletteRoute: typeof RouletteRoute
  SettingsRoute: typeof SettingsRoute
  VoiceRoute: typeof VoiceRoute
  ChatRoomIdRoute: typeof ChatRoomIdRoute
  DmNicknameRoute: typeof DmNicknameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$nickname': {
      id: '/dm/$nickname'
      path: '/dm/$nickname'
      fullPath: '/dm/$nickname'
      preLoaderRoute: typeof DmNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomId': {
      id: '/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof ChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  PeopleRoute: PeopleRoute,
  RouletteRoute: RouletteRoute,
  SettingsRoute: SettingsRoute,
  VoiceRoute: VoiceRoute,
  ChatRoomIdRoute: ChatRoomIdRoute,
  DmNicknameRoute: DmNicknameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
